name: Example Build Image

on:
  push:
    branches:
      - "prod"
    paths:
      - .github/workflows/build_deploy_prod.yaml
      - "worker/**"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: app
  ACCOUNT_ID: 254454736360
  TASKDEF_PATH: .aws/taskdef.json

permissions:
  id-token: write
  contents: read

jobs:
  build_and_register:
    name: Build Image and Register Task Definition
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Build image
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }} .

    - name: Tag image
      run: |
        docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Push image
      run: |
        docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Update image in taskdef.json
      run: |
        sed -i "s|<IMAGE_URI>|${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|g" ${{ env.TASKDEF_PATH }}

    - name: Register task definition
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://${{ env.TASKDEF_PATH }}
